server:
  port: 8888
spring:
  application:
    name: demo
  redis:
    host: 192.168.64.6
    port: 6379
    password: demo123456
    database: 1
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
  datasource:
    url: jdbc:mysql://192.168.64.3:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: aaaaa
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 300
      validation-query: "SELECT 1"
      test-on-borrow: true
      initial-size: 1
mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.examle.demo.dao
  mapper-locations: classpath*:generator/*.xml
